<?php

namespace App\Helpers;

class HtmlControlHelper
{

    /**
     * Note: the structure of $items is the one generated by the Dictionnaries::selectValues("xxx") method.
     *
     * @param string $name
     * @param array $items
     * @return string
     */
    public static function generateGroupedSelect(string $name, array $items)
    {
        $html = '<select class="form-select" name="' . htmlspecialchars($name) . '">';

        foreach ($items as $group) {
            $html .= '<optgroup label="' . htmlspecialchars($group['name']) . '">';

            foreach ($group['values'] as $id => $label) {
                $html .= '<option value="' . htmlspecialchars($id) . '">' . htmlspecialchars($label) . '</option>';
            }

            $html .= '</optgroup>';
        }

        $html .= '</select>';
        return $html;
    }
}