<?php

namespace App\Helpers;

use App\Accessors\Countries;

class PhoneCountryHelper
{

    private static $countryCallingCodes = null;
    private static $countryFlags = null;


    public static function selectable(): array
    {
        $flags      = self::getCountryFlags();
        $codes      = self::getCountryCallingCodes();
        $names      = Countries::getCode2Name();
        $selectable = [];
        foreach ($names as $code => $name) {
            $selectable[$code] = $name." ".$flags[$code]." ".$codes[$code];
        }

        return $selectable;
    }

    public static function getCountryCallingCodeByCountryCode(string $countryCode): string
    {
        return self::getCountryCallingCodes()[strtoupper($countryCode)] ?? '';
    }

    public static function getCountryFlagsByCountryCode(string $countryCode): string
    {
        return self::getCountryFlags()[strtoupper($countryCode)] ?? '';

    }


    public static function getCountryCallingCodes(): array
    {
        if (null === self::$countryCallingCodes) {
            self::$countryCallingCodes = [
                "AF" => "+93",    // Afghanistan
                "AL" => "+355",   // Albania
                "AQ" => "+672",   // Antarctica
                "DZ" => "+213",   // Algeria
                "AS" => "+1-684", // American Samoa
                "AD" => "+376",   // Andorra
                "AO" => "+244",   // Angola
                "AG" => "+1-268", // Antigua and Barbuda
                "AZ" => "+994",   // Azerbaijan
                "AR" => "+54",    // Argentina
                "AU" => "+61",    // Australia
                "AT" => "+43",    // Austria
                "BS" => "+1-242", // Bahamas
                "BH" => "+973",   // Bahrain
                "BD" => "+880",   // Bangladesh
                "AM" => "+374",   // Armenia
                "BB" => "+1-246", // Barbados
                "BE" => "+32",    // Belgium
                "BM" => "+1-441", // Bermuda
                "BT" => "+975",   // Bhutan
                "BO" => "+591",   // Bolivia
                "BA" => "+387",   // Bosnia and Herzegovina
                "BW" => "+267",   // Botswana
                "BV" => "",       // Bouvet Island (Uninhabited, no calling code)
                "BR" => "+55",    // Brazil
                "BZ" => "+501",   // Belize
                "IO" => "+246",   // British Indian Ocean Territory
                "SB" => "+677",   // Solomon Islands
                "VG" => "+1-284", // British Virgin Islands
                "BN" => "+673",   // Brunei Darussalam
                "BG" => "+359",   // Bulgaria
                "MM" => "+95",    // Myanmar
                "BI" => "+257",   // Burundi
                "BY" => "+375",   // Belarus
                "KH" => "+855",   // Cambodia
                "CM" => "+237",   // Cameroon
                "CA" => "+1",     // Canada
                "CV" => "+238",   // Cape Verde
                "KY" => "+1-345", // Cayman Islands
                "CF" => "+236",   // Central African Republic
                "LK" => "+94",    // Sri Lanka
                "TD" => "+235",   // Chad
                "CL" => "+56",    // Chile
                "CN" => "+86",    // China
                "TW" => "+886",   // Taiwan
                "CX" => "+61",    // Christmas Island
                "CC" => "+61",    // Cocos (Keeling) Islands
                "CO" => "+57",    // Colombia
                "KM" => "+269",   // Comoros
                "YT" => "+262",   // Mayotte
                "CG" => "+242",   // Congo
                "CD" => "+243",   // Congo, The Democratic Republic of the
                "CK" => "+682",   // Cook Islands
                "CR" => "+506",   // Costa Rica
                "HR" => "+385",   // Croatia
                "CU" => "+53",    // Cuba
                "CY" => "+357",   // Cyprus
                "CZ" => "+420",   // Czech Republic
                "BJ" => "+229",   // Benin
                "DK" => "+45",    // Denmark
                "DM" => "+1-767", // Dominica
                "DO" => "+1-809", // Dominican Republic
                "EC" => "+593",   // Ecuador
                "SV" => "+503",   // El Salvador
                "GQ" => "+240",   // Equatorial Guinea
                "ET" => "+251",   // Ethiopia
                "ER" => "+291",   // Eritrea
                "EE" => "+372",   // Estonia
                "FO" => "+298",   // Faroe Islands
                "FK" => "+500",   // Falkland Islands
                "GS" => "+500",   // South Georgia and the South Sandwich Islands
                "FJ" => "+679",   // Fiji
                "FI" => "+358",   // Finland
                "AX" => "+358",   // Åland Islands
                "FR" => "+33",    // France
                "GF" => "+594",   // French Guiana
                "PF" => "+689",   // French Polynesia
                "TF" => "+262",   // French Southern Territories
                "DJ" => "+253",   // Djibouti
                "GA" => "+241",   // Gabon
                "GE" => "+995",   // Georgia
                "GM" => "+220",   // Gambia
                "PS" => "+970",   // Palestinian Territory
                "DE" => "+49",    // Germany
                "GH" => "+233",   // Ghana
                "GI" => "+350",   // Gibraltar
                "KI" => "+686",   // Kiribati
                "GR" => "+30",    // Greece
                "GL" => "+299",   // Greenland
                "GD" => "+1-473", // Grenada
                "GP" => "+590",   // Guadeloupe
                "GU" => "+1-671", // Guam
                "GT" => "+502",   // Guatemala
                "GN" => "+224",   // Guinea
                "GY" => "+592",   // Guyana
                "HT" => "+509",   // Haiti
                "HM" => "",       // Heard Island and McDonald Islands (Uninhabited, no calling code)
                "VA" => "+379",   // Vatican City State
                "HN" => "+504",   // Honduras
                "HK" => "+852",   // Hong Kong
                "HU" => "+36",    // Hungary
                "IS" => "+354",   // Iceland
                "IN" => "+91",    // India
                "ID" => "+62",    // Indonesia
                "IR" => "+98",    // Iran
                "IQ" => "+964",   // Iraq
                "IE" => "+353",   // Ireland
                "IL" => "+972",   // Israel
                "IT" => "+39",    // Italy
                "CI" => "+225",   // Côte d'Ivoire
                "JM" => "+1-876", // Jamaica
                "JP" => "+81",    // Japan
                "KZ" => "+7",     // Kazakhstan
                "JO" => "+962",   // Jordan
                "KE" => "+254",   // Kenya
                "KP" => "+850",   // North Korea
                "KR" => "+82",    // South Korea
                "KW" => "+965",   // Kuwait
                "KG" => "+996",   // Kyrgyzstan
                "LA" => "+856",   // Laos
                "LB" => "+961",   // Lebanon
                "LS" => "+266",   // Lesotho
                "LV" => "+371",   // Latvia
                "LR" => "+231",   // Liberia
                "LY" => "+218",   // Libya
                "LI" => "+423",   // Liechtenstein
                "LT" => "+370",   // Lithuania
                "LU" => "+352",   // Luxembourg
                "MO" => "+853",   // Macao
                "MG" => "+261",   // Madagascar
                "MW" => "+265",   // Malawi
                "MY" => "+60",    // Malaysia
                "MV" => "+960",   // Maldives
                "ML" => "+223",   // Mali
                "MT" => "+356",   // Malta
                "MQ" => "+596",   // Martinique
                "MR" => "+222",   // Mauritania
                "MU" => "+230",   // Mauritius
                "MX" => "+52",    // Mexico
                "MC" => "+377",   // Monaco
                "MN" => "+976",   // Mongolia
                "MD" => "+373",   // Moldova
                "MS" => "+1-664", // Montserrat
                "MA" => "+212",   // Morocco
                "MZ" => "+258",   // Mozambique
                "OM" => "+968",   // Oman
                "NA" => "+264",   // Namibia
                "NR" => "+674",   // Nauru
                "NP" => "+977",   // Nepal
                "NL" => "+31",    // Netherlands
                "AN" => "+599",   // Netherlands Antilles
                "AW" => "+297",   // Aruba
                "NC" => "+687",   // New Caledonia
                "VU" => "+678",   // Vanuatu
                "NZ" => "+64",    // New Zealand
                "NI" => "+505",   // Nicaragua
                "NE" => "+227",   // Niger
                "NG" => "+234",   // Nigeria
                "NU" => "+683",   // Niue
                "NF" => "+672",   // Norfolk Island
                "NO" => "+47",    // Norway
                "MP" => "+1-670", // Northern Mariana Islands
                "UM" => "+1",     // United States Minor Outlying Islands
                "FM" => "+691",   // Micronesia
                "MH" => "+692",   // Marshall Islands
                "PW" => "+680",   // Palau
                "PK" => "+92",    // Pakistan
                "PA" => "+507",   // Panama
                "PG" => "+675",   // Papua New Guinea
                "PY" => "+595",   // Paraguay
                "PE" => "+51",    // Peru
                "PH" => "+63",    // Philippines
                "PN" => "+64",    // Pitcairn Islands
                "PL" => "+48",    // Poland
                "PT" => "+351",   // Portugal
                "GW" => "+245",   // Guinea-Bissau
                "TL" => "+670",   // Timor-Leste
                "PR" => "+1-787", // Puerto Rico
                "QA" => "+974",   // Qatar
                "RE" => "+262",   // Réunion
                "RO" => "+40",    // Romania
                "RU" => "+7",     // Russia
                "RW" => "+250",   // Rwanda
                "SH" => "+290",   // Saint Helena
                "KN" => "+1-869", // Saint Kitts and Nevis
                "AI" => "+1-264", // Anguilla
                "LC" => "+1-758", // Saint Lucia
                "PM" => "+508",   // Saint Pierre and Miquelon
                "VC" => "+1-784", // Saint Vincent and the Grenadines
                "SM" => "+378",   // San Marino
                "ST" => "+239",   // São Tomé and Príncipe
                "SA" => "+966",   // Saudi Arabia
                "SN" => "+221",   // Senegal
                "SC" => "+248",   // Seychelles
                "SL" => "+232",   // Sierra Leone
                "SG" => "+65",    // Singapore
                "SK" => "+421",   // Slovakia
                "VN" => "+84",    // Vietnam
                "SI" => "+386",   // Slovenia
                "SO" => "+252",   // Somalia
                "ZA" => "+27",    // South Africa
                "ZW" => "+263",   // Zimbabwe
                "ES" => "+34",    // Spain
                "EH" => "+212",   // Western Sahara
                "SD" => "+249",   // Sudan
                "SR" => "+597",   // Suriname
                "SJ" => "+47",    // Svalbard and Jan Mayen
                "SZ" => "+268",   // Eswatini
                "SE" => "+46",    // Sweden
                "CH" => "+41",    // Switzerland
                "SY" => "+963",   // Syria
                "TJ" => "+992",   // Tajikistan
                "TH" => "+66",    // Thailand
                "TG" => "+228",   // Togo
                "TK" => "+690",   // Tokelau
                "TO" => "+676",   // Tonga
                "TT" => "+1-868", // Trinidad and Tobago
                "AE" => "+971",   // United Arab Emirates
                "TN" => "+216",   // Tunisia
                "TR" => "+90",    // Turkey
                "TM" => "+993",   // Turkmenistan
                "TC" => "+1-649", // Turks and Caicos Islands
                "TV" => "+688",   // Tuvalu
                "UG" => "+256",   // Uganda
                "UA" => "+380",   // Ukraine
                "MK" => "+389",   // North Macedonia
                "EG" => "+20",    // Egypt
                "GB" => "+44",    // United Kingdom
                "IM" => "+44",    // Isle of Man
                "TZ" => "+255",   // Tanzania
                "US" => "+1",     // United States
                "VI" => "+1-340", // U.S. Virgin Islands
                "BF" => "+226",   // Burkina Faso
                "UY" => "+598",   // Uruguay
                "UZ" => "+998",   // Uzbekistan
                "VE" => "+58",    // Venezuela
                "WF" => "+681",   // Wallis and Futuna
                "WS" => "+685",   // Samoa
                "YE" => "+967",   // Yemen
                "CS" => "+381",   // Serbia and Montenegro
                "ZM" => "+260",   // Zambia
            ];
        }

        return self::$countryCallingCodes;
    }

    public static function getCountryFlags(): array
    {
        if (null === self::$countryFlags) {
            self::$countryFlags = [
                "AF" => "🇦🇫",   // Afghanistan
                "AL" => "🇦🇱",   // Albania
                "AQ" => "🇦🇶",   // Antarctica
                "DZ" => "🇩🇿",   // Algeria
                "AS" => "🇦🇸",   // American Samoa
                "AD" => "🇦🇩",   // Andorra
                "AO" => "🇦🇴",   // Angola
                "AG" => "🇦🇬",   // Antigua and Barbuda
                "AZ" => "🇦🇿",   // Azerbaijan
                "AR" => "🇦🇷",   // Argentina
                "AU" => "🇦🇺",   // Australia
                "AT" => "🇦🇹",   // Austria
                "BS" => "🇧🇸",   // Bahamas
                "BH" => "🇧🇭",   // Bahrain
                "BD" => "🇧🇩",   // Bangladesh
                "AM" => "🇦🇲",   // Armenia
                "BB" => "🇧🇧",   // Barbados
                "BE" => "🇧🇪",   // Belgium
                "BM" => "🇧🇲",   // Bermuda
                "BT" => "🇧🇹",   // Bhutan
                "BO" => "🇧🇴",   // Bolivia
                "BA" => "🇧🇦",   // Bosnia and Herzegovina
                "BW" => "🇧🇼",   // Botswana
                "BV" => "",     // Bouvet Island (Uninhabited, no calling code)
                "BR" => "🇧🇷",   // Brazil
                "BZ" => "🇧🇿",   // Belize
                "IO" => "🇮🇴",   // British Indian Ocean Territory
                "SB" => "🇸🇧",   // Solomon Islands
                "VG" => "🇻🇬",   // British Virgin Islands
                "BN" => "🇧🇳",   // Brunei Darussalam
                "BG" => "🇧🇬",   // Bulgaria
                "MM" => "🇲🇲",   // Myanmar
                "BI" => "🇧🇮",   // Burundi
                "BY" => "🇧🇾",   // Belarus
                "KH" => "🇰🇭",   // Cambodia
                "CM" => "🇨🇲",   // Cameroon
                "CA" => "🇨🇦",   // Canada
                "CV" => "🇨🇻",   // Cape Verde
                "KY" => "🇰🇾",   // Cayman Islands
                "CF" => "🇨🇫",   // Central African Republic
                "LK" => "🇱🇰",   // Sri Lanka
                "TD" => "🇹🇩",   // Chad
                "CL" => "🇨🇱",   // Chile
                "CN" => "🇨🇳",   // China
                "TW" => "🇹🇼",   // Taiwan
                "CX" => "🇨🇽",   // Christmas Island
                "CC" => "🇨🇨",   // Cocos (Keeling) Islands
                "CO" => "🇨🇴",   // Colombia
                "KM" => "🇰🇲",   // Comoros
                "YT" => "🇾🇹",   // Mayotte
                "CG" => "🇨🇬",   // Congo
                "CD" => "🇨🇩",   // Congo, The Democratic Republic of the
                "CK" => "🇨🇰",   // Cook Islands
                "CR" => "🇨🇷",   // Costa Rica
                "HR" => "🇭🇷",   // Croatia
                "CU" => "🇨🇺",   // Cuba
                "CY" => "🇨🇾",   // Cyprus
                "CZ" => "🇨🇿",   // Czech Republic
                "BJ" => "🇧🇯",   // Benin
                "DK" => "🇩🇰",   // Denmark
                "DM" => "🇩🇲",   // Dominica
                "DO" => "🇩🇴",   // Dominican Republic
                "EC" => "🇪🇨",   // Ecuador
                "SV" => "🇸🇻",   // El Salvador
                "GQ" => "🇬🇶",   // Equatorial Guinea
                "ET" => "🇪🇹",   // Ethiopia
                "ER" => "🇪🇷",   // Eritrea
                "EE" => "🇪🇪",   // Estonia
                "FO" => "🇫🇴",   // Faroe Islands
                "FK" => "🇫🇰",   // Falkland Islands
                "GS" => "🇬🇸",   // South Georgia and the South Sandwich Islands
                "FJ" => "🇫🇯",   // Fiji
                "FI" => "🇫🇮",   // Finland
                "AX" => "🇦🇽",   // Åland Islands
                "FR" => "🇫🇷",   // France
                "GF" => "🇬🇫",   // French Guiana
                "PF" => "🇵🇫",   // French Polynesia
                "TF" => "🇹🇫",   // French Southern Territories
                "DJ" => "🇩🇯",   // Djibouti
                "GA" => "🇬🇦",   // Gabon
                "GE" => "🇬🇪",   // Georgia
                "GM" => "🇬🇲",   // Gambia
                "PS" => "🇵🇸",   // Palestinian Territory
                "DE" => "🇩🇪",   // Germany
                "GH" => "🇬🇭",   // Ghana
                "GI" => "🇬🇮",   // Gibraltar
                "KI" => "🇰🇮",   // Kiribati
                "GR" => "🇬🇷",   // Greece
                "GL" => "🇬🇱",   // Greenland
                "GD" => "🇬🇩",   // Grenada
                "GP" => "🇬🇵",   // Guadeloupe
                "GU" => "🇬🇺",   // Guam
                "GT" => "🇬🇹",   // Guatemala
                "GN" => "🇬🇳",   // Guinea
                "GY" => "🇬🇾",   // Guyana
                "HT" => "🇭🇹",   // Haiti
                "HM" => "",     // Heard Island and McDonald Islands (Uninhabited, no calling code)
                "VA" => "🇻🇦",   // Vatican City State
                "HN" => "🇭🇳",   // Honduras
                "HK" => "🇭🇰",   // Hong Kong
                "HU" => "🇭🇺",   // Hungary
                "IS" => "🇮🇸",   // Iceland
                "IN" => "🇮🇳",   // India
                "ID" => "🇮🇩",   // Indonesia
                "IR" => "🇮🇷",   // Iran
                "IQ" => "🇮🇶",   // Iraq
                "IE" => "🇮🇪",   // Ireland
                "IL" => "🇮🇱",   // Israel
                "IT" => "🇮🇹",   // Italy
                "CI" => "🇨🇮",   // Côte d'Ivoire
                "JM" => "🇯🇲",   // Jamaica
                "JP" => "🇯🇵",   // Japan
                "KZ" => "🇰🇿",   // Kazakhstan
                "JO" => "🇯🇴",   // Jordan
                "KE" => "🇰🇪",   // Kenya
                "KP" => "🇰🇵",   // North Korea
                "KR" => "🇰🇷",   // South Korea
                "KW" => "🇰🇼",   // Kuwait
                "KG" => "🇰🇬",   // Kyrgyzstan
                "LA" => "🇱🇦",   // Laos
                "LB" => "🇱🇧",   // Lebanon
                "LS" => "🇱🇸",   // Lesotho
                "LV" => "🇱🇻",   // Latvia
                "LR" => "🇱🇷",   // Liberia
                "LY" => "🇱🇾",   // Libya
                "LI" => "🇱🇮",   // Liechtenstein
                "LT" => "🇱🇹",   // Lithuania
                "LU" => "🇱🇺",   // Luxembourg
                "MO" => "🇲🇴",   // Macao
                "MG" => "🇲🇬",   // Madagascar
                "MW" => "🇲🇼",   // Malawi
                "MY" => "🇲🇾",   // Malaysia
                "MV" => "🇲🇻",   // Maldives
                "ML" => "🇲🇱",   // Mali
                "MT" => "🇲🇹",   // Malta
                "MQ" => "🇲🇶",   // Martinique
                "MR" => "🇲🇷",   // Mauritania
                "MU" => "🇲🇺",   // Mauritius
                "MX" => "🇲🇽",   // Mexico
                "MC" => "🇲🇨",   // Monaco
                "MN" => "🇲🇳",   // Mongolia
                "MD" => "🇲🇩",   // Moldova
                "MS" => "🇲🇸",   // Montserrat
                "MA" => "🇲🇦",   // Morocco
                "MZ" => "🇲🇿",   // Mozambique
                "OM" => "🇴🇲",   // Oman
                "NA" => "🇳🇦",   // Namibia
                "NR" => "🇳🇷",   // Nauru
                "NP" => "🇳🇵",   // Nepal
                "NL" => "🇳🇱",   // Netherlands
                "AN" => "🇦🇳",   // Netherlands Antilles
                "AW" => "🇦🇼",   // Aruba
                "NC" => "🇳🇨",   // New Caledonia
                "VU" => "🇻🇺",   // Vanuatu
                "NZ" => "🇳🇿",   // New Zealand
                "NI" => "🇳🇮",   // Nicaragua
                "NE" => "🇳🇪",   // Niger
                "NG" => "🇳🇬",   // Nigeria
                "NU" => "🇳🇺",   // Niue
                "NF" => "🇳🇫",   // Norfolk Island
                "NO" => "🇳🇴",   // Norway
                "MP" => "🇲🇵",   // Northern Mariana Islands
                "UM" => "🇺🇲",   // United States Minor Outlying Islands
                "FM" => "🇫🇲",   // Micronesia
                "MH" => "🇲🇭",   // Marshall Islands
                "PW" => "🇵🇼",   // Palau
                "PK" => "🇵🇰",   // Pakistan
                "PA" => "🇵🇦",   // Panama
                "PG" => "🇵🇬",   // Papua New Guinea
                "PY" => "🇵🇾",   // Paraguay
                "PE" => "🇵🇪",   // Peru
                "PH" => "🇵🇭",   // Philippines
                "PN" => "🇵🇳",   // Pitcairn Islands
                "PL" => "🇵🇱",   // Poland
                "PT" => "🇵🇹",   // Portugal
                "GW" => "🇬🇼",   // Guinea-Bissau
                "TL" => "🇹🇱",   // Timor-Leste
                "PR" => "🇵🇷",   // Puerto Rico
                "QA" => "🇶🇦",   // Qatar
                "RE" => "🇷🇪",   // Réunion
                "RO" => "🇷🇴",   // Romania
                "RU" => "🇷🇺",   // Russia
                "RW" => "🇷🇼",   // Rwanda
                "SH" => "🇸🇭",   // Saint Helena
                "KN" => "🇰🇳",   // Saint Kitts and Nevis
                "AI" => "🇦🇮",   // Anguilla
                "LC" => "🇱🇨",   // Saint Lucia
                "PM" => "🇵🇲",   // Saint Pierre and Miquelon
                "VC" => "🇻🇨",   // Saint Vincent and the Grenadines
                "SM" => "🇸🇲",   // San Marino
                "ST" => "🇸🇹",   // São Tomé and Príncipe
                "SA" => "🇸🇦",   // Saudi Arabia
                "SN" => "🇸🇳",   // Senegal
                "SC" => "🇸🇨",   // Seychelles
                "SL" => "🇸🇱",   // Sierra Leone
                "SG" => "🇸🇬",   // Singapore
                "SK" => "🇸🇰",   // Slovakia
                "VN" => "🇻🇳",   // Vietnam
                "SI" => "🇸🇮",   // Slovenia
                "SO" => "🇸🇴",   // Somalia
                "ZA" => "🇿🇦",   // South Africa
                "ZW" => "🇿🇼",   // Zimbabwe
                "ES" => "🇪🇸",   // Spain
                "EH" => "🇪🇭",   // Western Sahara
                "SD" => "🇸🇩",   // Sudan
                "SR" => "🇸🇷",   // Suriname
                "SJ" => "🇸🇯",   // Svalbard and Jan Mayen
                "SZ" => "🇸🇿",   // Eswatini
                "SE" => "🇸🇪",   // Sweden
                "CH" => "🇨🇭",   // Switzerland
                "SY" => "🇸🇾",   // Syria
                "TJ" => "🇹🇯",   // Tajikistan
                "TH" => "🇹🇭",   // Thailand
                "TG" => "🇹🇬",   // Togo
                "TK" => "🇹🇰",   // Tokelau
                "TO" => "🇹🇴",   // Tonga
                "TT" => "🇹🇹",   // Trinidad and Tobago
                "AE" => "🇦🇪",   // United Arab Emirates
                "TN" => "🇹🇳",   // Tunisia
                "TR" => "🇹🇷",   // Turkey
                "TM" => "🇹🇲",   // Turkmenistan
                "TC" => "🇹🇨",   // Turks and Caicos Islands
                "TV" => "🇹🇻",   // Tuvalu
                "UG" => "🇺🇬",   // Uganda
                "UA" => "🇺🇦",   // Ukraine
                "MK" => "🇲🇰",   // North Macedonia
                "EG" => "🇪🇬",   // Egypt
                "GB" => "🇬🇧",   // United Kingdom
                "IM" => "🇮🇲",   // Isle of Man
                "TZ" => "🇹🇿",   // Tanzania
                "US" => "🇺🇸",   // United States
                "VI" => "🇻🇮",   // U.S. Virgin Islands
                "BF" => "🇧🇫",   // Burkina Faso
                "UY" => "🇺🇾",   // Uruguay
                "UZ" => "🇺🇿",   // Uzbekistan
                "VE" => "🇻🇪",   // Venezuela
                "WF" => "🇼🇫",   // Wallis and Futuna
                "WS" => "🇼🇸",   // Samoa
                "YE" => "🇾🇪",   // Yemen
                "CS" => "🇷🇸",   // Serbia and Montenegro
                "ZM" => "🇿🇲",   // Zambia
            ];
        }

        return self::$countryFlags;
    }
}
